---
output: pdf_document
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding, output_dir = "document_output")
      })
---

Dear Editor,

We are excited to submit our manuscript entitled "*Ecosystem size and complexity as extrinsic drivers of food chain length in branching ecosystems*" for consideration.

The structure of food webs in natural communities has inspired ecological research for generations, and much attention has been paid to understanding the determinants of food chain length. Generally, ecosystem size is thought to be a universal control of food chain length. In spatially complex ecosystems, however, there may be an overlooked effect of 'scale-invariant' complexity in fractal ecosystem structures. Branching river networks are an outstanding example of such complex ecosystems, where the geometric structure (e.g., branching pattern) remains constant across size gradients.

In this research, we developed a novel simulation model to investigate the influences of ecosystem size and complexity on food chain length in branching habitat networks. We found that ecosystem size and complexity both regulate food chain length (the "dual control"), but the strength of these regulations is modulated by disturbance regimes - the dual control was more apparent when disturbance is strong and frequent. However, other factors - such as food web structure and primary productivity - did not influence the qualitative relationships of food chain length and ecosystem structures, raising the possibility that the dual control of food chain length may emerge across a wide range of productivity and in diverse food webs.

Although ecosystems are inherently complex in space, there have been very limited efforts to investigate the role of ecosystem complexity in regulating food chain length. Our findings will stimulate future research addressing this critical research topic. Thus, our manuscript represents a novel contribution to food web ecology. In addition, the connection between network complexity and food web structure will be of interest to an interdisciplinary audience, including scientists working in fluvial geomorphology, ecological networks, and macrosystems ecology.

We suggest the following leading scientists in the field as potential reviewers:

-   Dr. Gaku Takimoto (University of Tokyo; [gakut\@es.a.u-tokyo.ac.jp](mailto:gakut@es.a.u-tokyo.ac.jp){.email}): Works on food web theory

-   Dr. Colette Ward (NCEAS, [ward\@nceas.ucsb.edu](mailto:ward@nceas.ucsb.edu){.email}): Works on theoretical food web ecology

-   Dr. Justin Yeakel (University of California Merced; [jdyeakel\@gmail.com](mailto:jdyeakel@gmail.com){.email}): Develops theoretical models for ecological communities, including species interactions in a spatial context

-   Dr. Kevin McCann (University of Guelph, [ksmccann\@uoguelph.ca](mailto:ksmccann@uoguelph.ca){.email}): Works on food web theory

-   Dr. Jean Gibert (Duke University; [jean.gibert\@duke.edu](mailto:jean.gibert@duke.edu){.email}): Develops general theoretical models for ecological communities

This work is original and is not under consideration in any other journal. All authors agree with the content and with the submission for publication, and all appropriate ethical and other necessary approvals were obtained for this research. We look forward to your reply and hope that you find our article suitable for publication in your journal.

Sincerely,

Justin Pomeranz, Jacques Finlay, Akira Terui

University of North Carolina Greensboro
