---
title: "Ecosystem size and complexity as extrinsic drivers of food chain length in branching ecosystems"
output: 
  # word_document:
  #   reference_docx: "word_format.docx"
  pdf_document:
   latex_engine: xelatex
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding, output_dir = "document_output")
      })
bibliography: references.bib
csl: https://www.zotero.org/styles/ecosphere
mainfont: Times New Roman
header-includes:
  \usepackage{lineno, textgreek}
  \linenumbers
---

```{r setup, include=FALSE}

library(tidyverse)

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE)

# Sensitivity data
df_sim <- readRDS(here::here("output/sim_main.rds")) %>% 
  filter(r_b %in% c(8, 16))

n_rep <- max(df_sim$n_rep)

n_scenario <- df_sim %>% 
  filter(sd_disturb_source > sd_disturb_lon) %>% 
  summarize(n = n_distinct(param_set)) %>% 
  pull(n)

n_sim <- df_sim %>% 
  mutate(n_sim = n_timestep + n_burnin + n_warmup) %>% 
  pull() %>% 
  unique()
```

Author: Justin P.F. Pomeranz^1,2^, Jacques C. Finlay^3^, Akira Terui^1^

1 Department of Biology, University of North Carolina at Greensboro; 2 Department of Environmental Sciences, Colorado Mesa University; 3 Department of Ecology, Evolution and Behavior, University of Minnesota

\*Corresponding Author: JPF Pomeranz, [jfpomeranz\@gmail.com](mailto:jfpomeranz@gmail.com){.email}; A Terui, [hanabi0111\@gmail.com](mailto:hanabi0111@gmail.com){.email}

# Abstract

Understanding the drivers of food chain length in natural communities has intrigued ecologists since Elton publicized 'food cycles' in the early 20th century. Proposed drivers of food chain length have included productivity, disturbance regime, ecosystem size, and trophic omnivory. However, current theories have largely assumed simple, two-dimensional habitat architectures and may not be adequate to predict food chain length in ecosystems with a complex, branching structure. Here, we develop a spatially explicit theoretical model which provides an integrated framework for understanding variation in food chain length in branching networks. We show independent, positive influences of ecosystem size and complexity on food chain length. However, these effects were contingent upon other drivers. In particular, the effects of ecosystem size and complexity appeared more clearly in high-disturbance and high-productivity regimes. Our results suggest that ecosystem complexity is an important yet overlooked driver of food chain length in branching ecosystems.

**Keywords:** Food chain length, omnivory, branching networks, fractals, intraguild predation, complex network architecture

## Data availability

No data were used or produced in this research. R functions for simulations are provided as the R package mcbrnet version 1.3.0 (available at <https://github.com/aterui/mcbrnet>). Codes for simulations, statistical analysis, figures, and tables are available at <https://github.com/aterui/public-proj_fcl-river-theory>.

\clearpage

# Introduction

The origin of variation in food chain length (FCL) has intrigued ecologists for decades due to its importance in regulating top-down effects [@paceTrophicCascadesRevealed1999], energy flow [@wangBiodiversityEcosystemFunctioning2018], and contaminant concentrations in top predators [@kiddEffectsTrophicPosition1998]. Hypotheses regarding controls of FCL can be organized into three broad categories. First, the resource availability hypothesis states that basal productivity controls FCL because imperfect energy conversion through predator-prey interactions restricts energy available to higher trophic levels [@oksanenExploitationEcosystemsGradients1981]. Second, the disturbance hypothesis (or the dynamical stability hypothesis) predicts longer food chains are vulnerable to environmental perturbations (i.e., the dynamical constraint). Thus, habitats with frequent and/or severe disturbance should support fewer trophic levels [@pimmNumberTrophicLevels1977]. Lastly, the ecosystem size hypothesis posits that larger ecosystems should harbor longer food chains [@takimotoEffectsProductivityDisturbance2012; @teruiSpatialDisturbanceSynchrony2019; @postEcosystemSizeDetermines2000].

Among the three hypotheses, the ecosystem size hypothesis has been consistently supported in empirical explorations, likely because it encompasses multiple mechanisms [@takimotoEnvironmentalDeterminantsFoodchain2013]. For example, large ecosystems have increased species richness (species-area relationship [@lomolinoEcologyMostGeneral2000]), are buffered against disturbances [@saboRoleDischargeVariation2010], and have greater numbers of immigrant sources in the ecosystem with stable metapopulations [@takimotoEnvironmentalDeterminantsFoodchain2013]. Meanwhile, the productivity and disturbance effects are highly sensitive to the internal structure of food webs [@postProximateStructuralMechanisms2007; @takimotoEffectsProductivityDisturbance2012]. As such, the effects of disturbance and resource availability on FCL have been found to be highly variable among ecosystem types and geographic regions [@takimotoEffectsProductivityDisturbance2012; @diehlIntraguildPreySuffer2001; @takimotoEnvironmentalDeterminantsFoodchain2013; @postLongShortFoodchain2002].

More recently, food web ecologists have begun to recognize that FCL rarely responds to a single driver, but instead is determined by interactions of multiple factors. For example, @wardMechanisticTheoryAquatic2017 showed that FCL was more responsive to increasing productivity in large ecosystems than small ones, whereas FCL was more sensitive to size in low-productivity systems. Such context-dependent responses to extrinsic factors seem to be tightly coupled with the arrangement of trophic links within a food web. For example, omnivory (feeding at multiple trophic levels) is a strong intrinsic driver of FCL [@takimotoEffectsProductivityDisturbance2012; @postProximateStructuralMechanisms2007; @woottonOmnivoryStabilityFreshwater2017]. When omnivory is absent in three-species communities, the trophic structure or "motif" assumes a simple linear food chain with a maximum trophic position of three (**Figure 1D**). However, FCL decreases with increasing omnivory as the top predator eats lower in the food web [@wardMechanisticTheoryAquatic2017; @woottonOmnivoryStabilityFreshwater2017]. Theoretical work predicts that food webs are destabilized when omnivory is too strong, leading to the loss of species and shorter food chains [@woottonOmnivoryStabilityFreshwater2017]. Conversely, weak omnivory stabilizes the food web and increases the persistence of species within a community, particularly at intermediate levels of productivity and high disturbance levels [@woottonOmnivoryStabilityFreshwater2017; @woottonManyWeakInteractions2016]. Due to the context-dependency of FCL to multiple drivers and the potential for interactive effects, a unified framework of multiple FCL drivers is needed to better understand when and where FCL will respond to these extrinsic and intrinsic factors. 

While recent research efforts of food web ecologists have substantially advanced our understanding of food chain drivers, theoretical conceptualization has implicitly assumed two-dimensional systems, which may be a fair approximation of lakes [@postEcosystemSizeDetermines2000; @doiResourceAvailabilityEcosystem2009] and oceanic islands [@takimotoEcosystemSizeNot2008]. However, many natural habitats have a high degree of spatial complexity that cannot be represented simply by ecosystem size. Branching ecosystems, for example, are ubiquitous yet overlooked landscape structures (e.g., rivers, trees, caves, mountain ranges) [@grantLivingBranchesPopulation2007; @altermattDiversityRiverineMetacommunities2013]. While we know that food web interactions are spatially influenced [@calcagnoConstraintsFoodChain2011; @pillaiMetacommunityTheoryExplains2011; @takimotoEffectsProductivityDisturbance2012; @teruiSpatialDisturbanceSynchrony2019], the theory to account for it has lagged, particularly in branching habitat architectures. Here, we theoretically explore drivers of FCL in rivers, an excellent example of branching ecosystems.

Ample evidence suggests that branching structure controls environmental heterogeneity and dispersal pathways for organisms within river ecosystems [@altermattDiversityRiverineMetacommunities2013; @tonkinRoleDispersalRiver2018]. Water and materials propagate downstream as small streams hierarchically join to form larger streams and rivers. Consequently, environmental signals (e.g., flood disturbance) are highly variable among tributaries while showing a strong within-tributary correlation [@nakamuraDisturbanceRegimesStream2000; @isaakSlowClimateVelocities2016; @mcguireNetworkAnalysisReveals2014; @abbottUnexpectedSpatialStability2018]. Confluences are merging points where tributary dynamics aggregate to form distinct environmental conditions in downstream habitat patches. Hence, habitat heterogeneity increases with branching complexity (**Figure 1A**), which we define here as the probability of branching per unit river distance. Highly-branched river networks provide diverse habitats that buffer the impact of large-scale environmental fluctuations, broadening opportunities for species to recolonize habitat patches post-disturbance [@teruiMetapopulationStabilityBranching2018]. Thus, ecosystem complexity in river networks may be a widespread yet overlooked extrinsic environmental driver of FCL.

We simulate trophic community dynamics within branching habitats to investigate the effects of extrinsic controls of FCL, such as ecosystem geometry [size (number of patches) and complexity (branching probability] and disturbance regime. In addition, our simulation model incorporates intrinsic drivers of FCL, including the degree of omnivory, productivity level, and species' dispersal ability, allowing us to assess the context dependency on drivers of FCL across extrinsic factors. We find that ecosystem size and complexity are both positively related to FCL, but the form of this relationship is dependent on other extrinsic and intrinsic factors. Our model is an important step in unifying drivers of FCL across extrinsic and intrinsic drivers and parsing their context-dependency in spatially complex ecosystems.

# Methods

## Network generation

We generated branching networks as connected habitat patches (**Figure 1A;** see **Table 1** for parameter notations). The geometric arrangement of networks was controlled by two parameters: ecosystem size, the number of patches ($N_{p}$); and ecosystem complexity, branching probability ($P_{b}$). Habitat patches were assigned to be a confluence (or upstream terminal patch) with probability $P_{b}$, or an in-branch patch with probability $1-P_{b}$. Branches (tributaries) are a series of connected patches between confluences (or upstream terminal patches). The number of patches within branch $q$, $n_{p,q}$, is a random variable drawn from a geometric distribution $n_{p,q} \sim \text{Ge}(P_{b})$ but conditional on $N_{p} = \sum_{q}^{N_{b}} n_{p,q}$ ($N_{b}$ is the number of branches in a network). Full details of the network generation process are described in @teruiEmergentDualScaling2021.

In our simulation, a disturbance occurs simultaneously across habitat patches with probability $p_m$, but the patches vary in their vulnerability. We simulated the spatial distribution of disturbance intensity (i.e., proportional mortality in the event of stochastic regional disturbance) as follows. A disturbance value, $m_{h}$, was assigned randomly to upstream terminal patch $h$ as $\text{logit}~m_{h} \sim \text{Normal}(\text{logit}~\mu_m, \sigma_{h}^2)$, where $\mu_m$ is the average of disturbance intensity at headwaters in an ordinary scale. The disturbance values propagate downstream through a spatial autoregressive process as:

$$
\begin{aligned}
\text{logit}~m_{down} &= \text{logit}~m_{up}+ \varepsilon &&\text{(1)}
\end{aligned}
$$

where $m_{down}$ and $m_{up}$ are the disturbance values at down- and upstream patches, and the local environmental noise at the downstream patch $\varepsilon$ was drawn from $\text{Normal}(0, \sigma_{l}^2)$. This autoregressive process resembles a natural disturbance regime, where flood or drought disturbance cascades downstream with some local variation along the channel [@nakamuraDisturbanceRegimesStream2000]. At confluence patches, the disturbance value takes a weighted mean based on the relative size of the two contributing branches, $Q$ (the number of upstream contributing patches + 1):

$$
\begin{aligned}
\text{logit}~m_{down} &= \omega~(\text{logit}~m_{1,up} +\varepsilon_1)+(1-\omega)~(\text{logit}~m_{2,up} +\varepsilon_2) &&\text{(2)}
\end{aligned}
$$

$m_{1,up}$ and $m_{2,up}$ are the disturbance values of upstream contributing tributaries, $\varepsilon_1$ and $\varepsilon_2$ are independent local noises, and $\omega$ the relative size of one tributary over another defined as $\omega = \frac{Q_{1}}{Q_{1} + Q_{2}}$. Thus, the larger tributary has a greater influence on the downstream environment, as observed in natural river networks [@bendaNetworkDynamicsHypothesis2004]. Disturbance value distributions had medians close to $\mu_m$ with long tails (**Figure 1B**). The low-magnitude patches can be viewed as refugia, which supply individuals to impacted sites in subsequent time steps.

We also mimicked the downstream increase of local carrying capacity reflecting downstream increases in algal resource availability [@teruiThreeEcologicalFactors2016; @carraraComplexInteractionDendritic2014; @rahelFishAssemblagesHabitat1991]. Carrying capacity in patch $x$, $K_x$, was assumed to increase as a power function of ecosystem area (i.e., watershed area) [@finlayStreamSizeHuman2011; @koenigEmergentProductivityRegimes2019]: 

$$
\begin{aligned}
K_{x} &= K_{base}Q_{x}^z &&\text{(3)}
\end{aligned}
$$

where $K_{base}$ is the carrying capacity at the upstream terminal patch, and $z$ is the scaling exponent. In this formulation, the most upstream patch, at which $Q_x = 1$ (the number of upstream patches + 1), has the carrying capacity of $K_{base}$. We used $z = 0.54$ based on an empirical relationship between gross primary production and watershed area [@finlayStreamSizeHuman2011]. 

## Tri-trophic model

We employed a discrete-time model to describe tri-trophic dynamics in each habitat patch (see **Table 1** for parameter notations). A discrete model is suitable for organisms with predictable reproduction cycles, a common life history for many lotic species, including macroinvertebrates and fish. Our simulation model consists of three species; a basal species $B$ with positive logistic growth up to a carrying capacity, $K$; a primary consumer species or intraguild prey, $C$, which grows based on the consumption of $B$; and an intraguild predator $P$, which can consume both $B$ and $C$ (**Figure 1C**). The realized species abundance $A_{ix,t+1}$ for species $i$ (either $B,C,~or~P$) at patch $x$ and time $t+1$ is expressed as a composite of within-patch trophic interactions, immigration, and emigration:

$$
\begin{aligned}
A_{ix,t+1} &\sim \text{Poisson}(\bar{A}_{ix,t} + I_{ix,t} - E_{ix,t}) &&\text{(4)}
\end{aligned}
$$

where $\bar{A}_{ix,t}$ is the expected species abundance after within-patch trophic interactions, $I_{ix,t}$ the expected number of immigrants into patch $x$, and $E_{ix,t}$ the expected number of emigrants from patch $x$. The realized discrete number of individuals is drawn from a Poisson distribution to account for stochasticity in demographic and dispersal processes.

***Internal dynamics.*** Each time step starts with internal dynamics. The general formula is the extension of the Nicholson-Bailey model [@hassellSpatialTemporalDynamics2000], which is given as follows:

$$
\begin{aligned}
B^+_{x,t} &= B_{x,t}g(B_{x,t})f_1(B'_{x,t}, C_{x,t})f_2(B'_{x,t}, P_{x,t}) &&\text{(5a)}\\
C^+_{x,t} &= e_{BC}B'_{x,t}[1 - f_1(B'_{x,t}, C_{x,t})]f_3(C'_{x,t}, P_{x,t}) &&\text{(5b)}\\
P^+_{x,t} &= e_{BP}B'_{x,t}f_1(B'_{x,t}, C_{x,t})[1 - f_2(B''_{x,t}, P_{x,t})] + e_{CP}C_{x,t}[1 - f_3(C'_{x,t}, P_{x,t})]
&&\text{(5c)}
\end{aligned}
$$

where $e_{ij}$ is the energetic conversion efficiency from $i$ to $j$. The function $g(\cdot)$ defines the density-dependent recruitment for the basal species, and the function $f_k(\cdot)$ dictates the proportion of survived prey individuals after predation. In the above equations, we re-defined variables as follows to simplify the expression:

$$
\begin{aligned}
B'_{x,t} &= B_{x,t}g(B_{x,t}) &&\text{B's recruitment} &&&\text{(6a)}\\
B''_{x,t} &= B'_{x,t}f_1(B'_{x,t}, C_{x,t}) &&\text{C's predation on B} &&&\text{(6b)}\\
C'_{x,t} &= e_{BC}B'_{x,t}[1 - f_1(B'_{x,t}, C_{x,t})] &&\text{C's recruitment} &&&\text{(6c)}
\end{aligned}
$$

The model assumes that ecological events occur in the following order: (1) $B$'s recruitment, (2) $C$'s predation on $B$ followed by $C$'s recruitment, and (3) $P$'s predation on $B$ and $C$ followed by $P$'s recruitment. We assumed that the intraguild prey $C$ consumes the basal species $B$ first because the species is specialized to prey on $B$.

We used the Beverton-Holt function to describe the density-dependent growth of the basal species:

$$
\begin{aligned}
g(B_{x,t}) = \frac{r_{b}} {1 + \frac{r_b - 1}{K_{x}}B_{x,t}} &&\text{(7)}
\end{aligned}
$$

where $r_{B}$ is the intrinsic growth rate and $K_x$ is the carrying capacity at patch $x$. We assumed the Type-II functional response in the survival function $f_k(\cdot)$ as follows [@hassellSpatialTemporalDynamics2000; @weideHydraEffectParadox2019]:

$$
\begin{aligned}
f_1(B'_{x,t}, C_{x,t}) &= \exp \left(-\frac{a_{BC} C_{x,t}} {1 + a_{BC} h_{BC} B'_{x,t}} \right) &&\text{C on B} &&&\text{(8a)}\\
f_2(B''_{x,t}, P_{x,t}) &= \exp \left(-\frac{(1 + \phi) a_{BP} P_{x,t}} {1 + a_{BP} h_{BP} B''_{x,t}} \right) &&\text{P on B} &&&\text{(8b)}\\
f_3(C'_{x,t}, P_{x,t}) &= \exp \left(-\frac{(1 - \phi) a_{CP} P_{x,t}} {1 + a_{CP} h_{CP} C'_{x,t}} \right) &&\text{P on C} &&&\text{(8c)}
\end{aligned}
$$

The parameter $a_{ij}$ defines $j$'s attack rate to $i$, $h_{ij}$ the handling time, and $\phi$ the switching function for the intraguild predator. We assumed that switching is dependent on the relative abundance of $B''_{x,t}$ and $C'_{x,t}$ [@hassellSpatialTemporalDynamics2000]:

$$
\begin{aligned}
\phi = \frac{s(B''_{x,t} - C'_{x,t})}{B''_{x,t} + C'_{x,t}} &&\text{(9)}
\end{aligned}
$$

where the parameter $s$ determines the strength of switching ($0 \le s \le 1$). In this expression, the intraguild predator increases its attack rate to the basal species if $\phi > 0$, properly representing the switching behavior of the intraguild prey.

***Disturbance.*** After recruitment, all species experience proportional loss if a stochastic regional disturbance occurs:

$$
\begin{aligned}
\bar{A}_{ix,t}(t) &= A^+_{ix,t} (1 - \nu_t m'_{x,t}) &&\text{(10)}
\end{aligned}
$$

where $m'_{x,t}$ is the disturbance intensity at patch $x$ and time $t$, which was drawn from a Beta distribution with mean $m_x$ and precision $1000$. The mean disturbance intensity $m_x$ is determined by the network generation process. The random variable $\nu_t$ represents the incidence of regional disturbance ($\nu_t = 1$ if a disturbance occurs, otherwise zero), which is drawn from a Bernoulli distribution as $\nu_t \sim \text{Bernouilli}(p_m)$.

***Dispersal.*** We simulated distance-dependent dispersal along with a network. The number of emigrants from patch $x$ at time $t$, $E_{ix,t}$, is estimated as the product of dispersal probability $p_{d}$ and species abundance after internal dynamics $\bar{A}_{ix,t}$. The dispersal probability was assumed to be constant for all three species. We calculated the relative immigration potential $\xi_{ix,t}$ considering network structure and species dispersal capability as follows:

$$
\begin{aligned}
\xi_{ix,t} &= \frac{\sum_{y, y \ne x}E_{iy,t}\exp(-\theta d_{xy})}{\sum_{x} \sum_{y, y \ne x}E_{iy,t}\exp(-\theta d_{xy})}
&&\text{(11)}
\end{aligned}
$$

where $d_{xy}$ is the network distance between patch $x$ and $y$ (shortest path), and $\theta$ indicates the inverse of mean dispersal distance (i.e., larger numbers mean shorter dispersal distance). The immigration potential at patch $x$, $\sum_{y, y \ne x}E_{iy,t}\exp(-\theta d_{xy})$, is scaled by the sum of immigration potential across patches so that $\sum_{x} \xi_{ix,t}=1$. The expected number of immigrants into patch $x$ is calculated as $I_{ix,t}=\xi_{ix,t} \sum_{x}E_{ix,t}$.

***Food chain length.*** At each patch and time step, we determined local FCL as the highest trophic position ($\tau_{x,t}$) of the existing species. When the predator exists, the trophic position is determined as follows:

$$
\begin{aligned}
\tau_{x,t} &= \delta_{x,t} + 2(1 - \delta_{x,t}) + 1
&&\text{(12)}
\end{aligned}
$$

where $\delta_{x,t}$ is the derived parameter that represents the degree of omnivory and is defined as:

$$
\begin{aligned}
\delta_{x,t} = \frac{e_{BP}B'_{x,t}f_1(B'_{x,t}, C_{x,t})[1 - f_2(B''_{x,t}, P_{x,t})]}{P^+_{x,t}} &&\text{(13)}
\end{aligned}
$$

Thus, our definition accounts for the influence of omnivory. We defined the global FCL $\bar{\tau}$ across patches $N_p$ and time $T$ as $\bar{\tau} = \frac{\sum_x \sum_t \tau_{x,t}}{N_p T}$ (i.e., average over space and time).

## Simulation

Prior to the main simulation, we performed one-patch simulations to explore the predation parameter space ($a_{ij}$ and $h_{ij}$) that allows stable coexistence of the three species without disturbance and dispersal (see **Supporting Information**). In this simulation, we assumed $h_{ij} = h$ to reduce the dimension of parameter space. This analysis revealed that the stable coexistence of the three species is possible with certain combinations of predation parameters. Within this parameter space, we used three parameter combinations to represent distinctive food webs with varied levels of omnivory: "chain (no omnivory)" $(a_{BC}, a_{BP}, a_{CP}, h) = (0.5, 0, 0.0025, 0.5)$, "weak omnivory" ($0.5, 0.02, 0.025, 0.5$), and "strong omnivory" ($0.5, 0.04, 0.0025, 0.75$). We used $s = 1$ except for the chain scenario with $s = 0$. Without the loss of generality, we assumed $e_{ij} = e = 1$.

Under each motif, we crossed values of disturbance (frequency and intensity), productivity, and dispersal. Disturbance frequency and intensity were controlled via $p_m$ ( `r unique(df_sim$p_disturb) %>% sort()`) and $\mu_m$ (`r unique(df_sim$mean_disturb_source) %>% sort()`), respectively. Spatial disturbance patterns were regulated by variation in disturbance intensity at headwaters ($\sigma_{h}=$ `r max(df_sim$sd_disturb_source)`), and local variation ($\sigma_{l}=$ `r min(df_sim$sd_disturb_lon)`). This setup ($\sigma_h > \sigma_l$) produces high spatial variation among tributaries while allowing strong within-tributary downstream correlation [@teruiEmergentDualScaling2021], a typical pattern in real river networks [@nakamuraDisturbanceRegimesStream2000; @bendaNetworkDynamicsHypothesis2004]. We used a combination of basal species' growth rate $r_b$ and base carrying capacity $K_{base}$ (low productivity: $r_b =$ `r min(df_sim$r_b)`, $K_{base} =$ `r min(df_sim$base_k)` ; high productivity = $r_b =$ `r max(df_sim$r_b)`, $K_{base} =$ `r max(df_sim$base_k)` ) as a proxy for resource availability. For dispersal, we examined short- and long-distance dispersal scenarios (short-distance dispersal $\theta=$ `r max(df_sim$theta)`; long-distance dispersal $\theta=$ `r min(df_sim$theta)`) with constant dispersal probability ($p_{d}=$ `r unique(df_sim$p_dispersal)`). Parameter values were summarized in **Table 1**.

We ran `r max(df_sim$n_rep)` simulation replicates with `r n_sim` timesteps of trophic dynamics (including `r n_sim - unique(df_sim$n_timestep)` steps of warmup and burn-in). During the warmup period (`r unique(df_sim$n_warmup)` time steps), we introduced propagules into habitat patches every 10 time steps to allow species to establish populations. Propagules are random draws from $\text{Poisson}(\lambda)$ ($\lambda=100, 10,~\text{and}~1$ for $B$, $C$, and $P$, respectively). Subsequently, we ran a burn-in period with no propagules for `r unique(df_sim$n_burnin)` time steps to remove the effects of initial conditions. Note that simulation replicates differ in ecosystem size ($N_{p}\sim \text{Unif}(10,150)$) and ecosystem complexity ($P_{b} \sim \text{Unif}(0.01, 0.99)$) so we can estimate their effects on FCL.

We obtained the global FCL $\bar{\tau}$ for the last `r unique(df_sim$n_timestep)` time steps. We also calculated the proportion of the patch state ("no species", "B", "B + C", "B + P", and "B + C + P") to infer mechanisms that drive changes in FCL. All analysis was performed in R 4.2.1 [@rcoreteamLanguageEnvironmentStatistical2021]

# Results

## Overall effects of ecosystem geometry

There were two consistent patterns in the relationship between FCL and ecosystem geometry (size and complexity). First, the effects of ecosystem size and complexity were modulated by disturbance. Second, productivity strengthened the relationship between FCL and ecosystem geometry with important direct effects that were motif dependent. Third, dispersal had a minimal but non-negligible positive effect on FCL. Below we describe these results in detail.

## Interactive effect of ecosystem geometry and disturbance

Ecosystem geometry interacted with disturbance to dictate FCL in branching ecosystems (**Figures 2 and 3**). With no disturbance, both geometric features (size and complexity) had limited influence on FCL. However, as disturbance frequency increases, the relationships between FCL and ecosystem geometry become positive. This interactive effect emerged because the sensitivity of FCL to disturbance depended on ecosystem geometry. Although increased disturbance frequency reduced overall FCL, smaller and/or simpler ecosystems exhibited greater vulnerability (**Figures 2 and 3**). Therefore, disturbance interacted with ecosystem geometry to produce the interdependence of these factors in determining FCL. However, the maximum levels of FCL were strongly regulated by disturbance frequency, highlighting the important direct effect of disturbance. It is important to note that the interactive effects were not observed with low disturbance intensity (**Figures S3 and S4**); this suggests that disturbance intensity must be strong enough to be influential.

The exception is the chain scenario (no omnivory) with no disturbance and low productivity. In this scenario, ecosystem size had a positive effect on FCL (**Figure 2**), while ecosystem complexity had a negative influence (**Figure 3**). These opposing influences of ecosystem size and complexity were associated with their contrasting relationships with the total carrying capacity (i.e., carrying capacity summed across all patches): ecosystem size increased the total carrying capacity, whereas ecosystem complexity decreased it (**Figure S10**). However, these patterns characteristic of the chain scenario diminished when considering some levels of omnivory.

State transitions shed light on how FCL changes occurred. In the chain motif, an additive mechanism (i.e., the addition of higher trophic species) was always responsible for the changes in FCL. With disturbance, state transition occurs from "B" to "B + C" (low productivity) or "B + C" to "B + C + P" (high productivity) as ecosystem size or complexity increases. Exceptionally, the state transition of "B + C + P" $\rightarrow$ "B + C" occurred as ecosystem complexity increased with no disturbance and low productivity, a scenario in which ecosystem complexity decreased FCL.

In the weak and strong omnivory motifs, ecosystem size and complexity increased FCL through different mechanisms. Ecosystem size increased FCL primarily through additive mechanisms, facilitating the state transition of "B" $\rightarrow$ "B + P" (low productivity) or "No species" $\rightarrow$ "B + P" (high productivity), particularly with frequent disturbance (**Figure S5**). In contrast, insertion (i.e., the insertion of intermediate trophic species) and additive mechanisms were responsible for the effect of ecosystem complexity. With weak omnivory, the transition from "B + P" to "B + C + P" (insertion) was predominant when productivity was low (**Figure S6B**). However, the additive mechanism ("No species" $\rightarrow$ "B + P") took primacy in the high productivity scenario (**Figure S6B**). In the strong omnivory motif, transition patterns depended on disturbance frequency. When disturbance was rare ($p_m = 0.05$), the insertion mechanism ("B + P" $\rightarrow$ "B + C + P") drove the FCL change (**Figure S6C**). As disturbance frequency increased, the primary process switched to an additive mechanism ("B" $\rightarrow$ "B + P" or "No species" $\rightarrow$ "B + P"; **Figure S6C**).

## Productivity effect

High productivity strengthened the relationship between FCL and ecosystem geometry. In the chain motif, productivity greatly increased the overall FCL (**Figure S7**), thereby shifting the upper bound of FCL (**Figures 2 and 3**). In contrast, increased productivity greatly decreased the minimum levels of FCL with weak and strong omnivory with little influence on the maximum FCL (**Figures 2, 3, and S7**). This negative effect of increased productivity was apparent in smaller and/or simpler ecosystems, steepening the slopes between FCL and ecosystem geometry (**Figures 2 and 3**).

State transitions associated with increased productivity depended on the motif structure. In the chain motif, the transition from "B + C" to "B + C + P" was dominant regardless of disturbance frequency (**Figure S8**). The introduction of omnivory allowed the transition between "B + P" and "B + C + P". With weak omnivory, the transition of "B + C + P" $\rightarrow$ "B + P" was prevalent and shortened FCL across disturbance regimes (**Figure S8**). However, this transition was marginal in the strong omnivory motif. Instead, productivity significantly increased the proportion of the "No species" state (**Figure S8**) in disturbed scenarios, especially in small and/or simple ecosystems (**Figures S5 and S6**).

## Dispersal effect

Dispersal distance had a positive influence on FCL regardless of simulation scenarios (**Figure S7**). However, this direct effect was weak in comparison to other factors.

State transitions occurred through an additive (chain) or insertion mechanism (omnivory). In the chain motif, the transitions were either "B" $\rightarrow$ "B + C" or "B + C" $\rightarrow$ "B + C+ P", depending on disturbance frequency (**Figure S9**). In the omnivory motifs, the predominant transition was from "B + P" to "B + C + P" (**Figure S9**).

# Discussion

The ecosystem size hypothesis of FCL has received support from both theoretical and empirical research [@vanderzandenPatternsFoodChain1999; @postEcosystemSizeDetermines2000; @takimotoEffectsProductivityDisturbance2012], although empirical work so far has rarely elaborated on the underlying drivers [but see @saboRoleDischargeVariation2010; @wardMechanisticTheoryAquatic2017]. In contrast, ecosystem complexity has not been incorporated in theoretical explorations of FCL to date. Here, we show that FCL responds positively to increasing ecosystem size and complexity, assessed as the number of patches and branching probability in river networks. This supports our hypothesis that ecosystem complexity may represent an overlooked yet important extrinsic control of FCL. However, the relationship between FCL and ecosystem complexity varied with other extrinsic and intrinsic factors, supporting the emerging paradigm that FCL is regulated by multiple factors [@mchughDualInfluencesEcosystem2010; @wardMechanisticTheoryAquatic2017]. Although we focus on river networks here, we expect our results to be transferable to other systems with non-branching structures. Ecosystems are intrinsically complex -- forests possess complex vertical and horizontal structures, which may provide heterogeneous microhabitats with different levels of vulnerability to wind and/or fire disturbances [@canslerClimateFireSize2014; @petersonContagiousDisturbanceEcological2002; @rommeHistoricalPerspectiveYellowstone1989]. Topographic and terrain variation can also mediate spatial disturbance patterns in a landscape [@connell30YearStudy1997; @stueveSpatialPatternsIce2007]. Explicit consideration of ecosystem complexity may therefore increase our ability to predict FCL and complements spatial food web theory that has emerged over the past two decades [@holtFoodWebsSpace2002a; @mccannDynamicsSpatiallyCoupled2005; @pillaiMetacommunityTheoryExplains2011; @takimotoEffectsProductivityDisturbance2012; @andersonEffectsDispersalRiver2018; @teruiSpatialDisturbanceSynchrony2019].

The most significant finding in this study is the synergistic effects between ecosystem geometry and disturbance. Our no-disturbance scenario can be viewed as habitat networks having nearly homogeneous environments, in which long food chains were generally supported independently of ecosystem size and complexity (except the chain motif with low productivity). However, as the frequency of intense disturbance increases, small and/or simple networks become unable to maintain long food chains. Here, increased ecosystem size and complexity may give greater resistance to disturbance through different mechanisms. Ecosystem size increases the "total amount" of disturbance refugia, from which dispersing propagules recolonize impacted habitat patches. In the meantime, ecosystem complexity may increase the connectivity to disturbance refugia. Branching shortens the mean distance between patches and, therefore, may enhance immigration from less disturbed patches (**Figure S10**). The proportion of disturbance refugia may also have increased in more branched networks. However, we did not observe a clear proportional increase in disturbance refugia with increasing branching probability (**Figure 1B**). Collectively, each of the geometric features likely supports long food chains through distinct mechanisms, which may also explain the different patterns of state transitions (additive vs. insertion mechanisms) [@postProximateStructuralMechanisms2007]. We must note that, however, the effects of ecosystem size and complexity were  limited to small to intermediate levels. In large or complex ecosystems, dispersal propagules may not be a limiting factor of FCL as the supply is plenty; therefore, productivity or omnivory more strongly regulated FCL (**Figures 2 and 3**) as predicted by previous theory [@takimotoEffectsProductivityDisturbance2012]

While empirical studies rarely looked at the influence of ecosystem complexity on FCL, several studies provide some support for this theoretical prediction. For example, @sullivanEcosystemStructureEmerges2015 reported FCL is controlled primarily by the number of tributary confluences in Idaho streams. Similarly, it has been shown that the merging of major tributaries lengthened FCL in the Colorado River, especially during a post-monsoon turbid water phase [@saboPulsedFlowsTributary2018]. More empirical research is needed to confirm our theoretical predictions.

The synergy between ecosystem geometry and disturbance also has an important implication for why the disturbance hypothesis has been least supported by the literature [@takimotoEnvironmentalDeterminantsFoodchain2013]. Although increased disturbance frequency consistently reduced FCL, its magnitude depended strongly on ecosystem geometry. This observation should provide a possible explanation for the mixed effects of disturbance in field studies. Although FCL research often assumes that the effects of environmental controls are independent, exploring potential interactions among them could provide useful insights into environmental controls of FCL in nature.

Our results are crucial given that anthropogenic climate change is predicted to increase the frequency and magnitude of disturbances [@brunnerFutureStreamflowRegime2020; @mittalImpactHumanIntervention2016]. River networks are especially vulnerable due to their propensity to go dry during droughts [@zipperPervasiveChangesStream2021] as well as susceptibility to more intense flood disturbance with increasing storm intensity [@schiermeierIncreasedFloodRisk2011]. Therefore, the preservation of habitat diversity conferred by ecosystem size and complexity is critical to biodiversity conservation under rapid environmental changes. In addition, maintaining dispersal corridors is important because the effect of spatial refuges can emerge only through recolonization after disturbance. Dams and road crossings have altered the connectivity between suitable habitat patches or have completely blocked dispersal [@ishiyamaPredictingEcologicalImpacts2018; @moritaEffectsHabitatFragmentation2002; @perkinFragmentationAltersStream2012]. Light pollution has also negatively affected the ability of adult aquatic insects to disperse between habitat patches [@perkinEffectsArtificialLighting2014]. These human activities may increase the vulnerability of food webs to rapid environmental changes.

Another interesting result of our simulation is the interaction with omnivory. In particular, with no disturbance and low productivity, the FCL of the chain motif had contrasting relationships with ecosystem size (positive) and complexity (negative). It is evident from the one-patch simulation that the chain motif is highly sensitive to local carrying capacity (**Figures S1 and S2**); therefore, FCL followed the changes in the total carrying capacity along the gradients of ecosystem size and complexity. These relationships diminished in omnivory motifs as the dependence of FCL on local carrying capacity weakened or reversed (**Figures S1 and S2**). Importantly, however, disturbance overwhelmed the role of omnivory in modulating the FCL-geometry relationships: as the frequency of intense disturbance increases, the positive relationships between FCL and ecosystem geometry emerged regardless of omnivory levels. This result could explain the consistent support for the ecosystem size hypothesis in various ecosystems [@takimotoEnvironmentalDeterminantsFoodchain2013] and raises the possibility of ecosystem complexity as an important control of FCL in branching networks. Our results also imply that if disturbance is strong and frequent, the effects of ecosystem geometry are robust to food web reorganization, which is often associated with species extirpations or introductions. The strength of omnivory in these novel communities can be increased or decreased, depending on the introduced species and the extant species pool or community. For example, non-indigenous fishes in the Eastern Mediterranean Sea outcompete native species for high-quality prey items, causing native species to increase their consumption of non-preferred prey items [@fanelliDepictingNovelEastern2015]. Yet, such substantial food web reorganization may not alter qualitative relationships between FCL and ecosystem geometry.

The effect of productivity was motif-dependent, supporting previous theoretical predictions [@postProximateStructuralMechanisms2007; @kondohFoodchainLengthAdaptive2009; @wardMechanisticTheoryAquatic2017]. While productivity clearly increased FCL in the chain motif, the productivity effect was negative in omnivory motifs. Intraguild predation plays an important role in explaining this context dependency. In the high productivity scenario with omnivory, the increased abundance of the basal species enhances the intraguild predator. This may subsequently facilitate the local exclusion of the intraguild prey through increased predation pressure if the attack rate is sufficiently high [@postProximateStructuralMechanisms2007]. Indeed, in the weak omnivory motif (the high value of the attack rate of P on C), we observed the state transition from "B + C + P" to "B + P" with shortened FCL regardless of disturbance frequency. However, this was not the case in the strong omnivory motif; the increased proportion of the "No species" state strongly impacted the minimum FCL, and this transition was mediated by disturbance. This result suggests that, although the strong omnivory motif is innately stable with high productivity (see one-patch simulations; **Figures S1 and S2**), external disturbance undermines the sensitive balance of predator-prey interactions with the abrupt increase of "No species" state, which must be countered by immigration from less disturbed habitats to maintain food chains.

It is therefore probable that different processes underlie the productivity-driven enforcement of the FCL-geometry relationships even within omnivory motifs. With the weak omnivory motif, productivity facilitated the spatial spread of the intraguild predator in small ecosystems, where dispersing propagules can reach most areas of a network with local extirpation of the intraguild prey. In the strong omnivory motif, increased productivity magnified the disproportionate impact of disturbance on small and/or simple ecosystems because the motif seems highly susceptible to disturbance with a limited supply of immigrants. 

Our findings add an important distinction to work to assess and prioritize protection or conservation status within human-impacted regions. Classical conservation schemes emphasize ecosystem size, aiming to protect the largest areas possible [@diamondIslandDilemmaLessons1975]. While this is certainly a useful attribute generally, designating networks with a high degree of variability, or many small patches, can be more beneficial than a large, homogeneous area [@fahrigWhySeveralSmall2020]. In the context of river networks, our results suggest that branching architectures may guide the spatial design of conservation actions. For example, regional food webs may be better protected if small reserves are placed widely across different tributaries with unique environmental conditions [@koningNetworkGrassrootsReserves2020; @teruiEmergentDualScaling2021]. This implication aligns with modern conservation initiatives, in which conservation and management should focus on activities that increase the habitat heterogeneity and connectivity of suitable habitat patches to increase resilience to predicted increases in disturbance frequency and magnitude [@schindlerPopulationDiversityPortfolio2010; @schindlerPortfolioConceptEcology2015; @andersonPortfolioConservationMetapopulations2015]. Considering ecosystem complexity is useful especially when direct information for spatial environmental heterogeneity is lacking because ecosystem complexity, such as branching probability, can be estimated from widely-available GIS layers [@teruiMetapopulationStabilityBranching2018; @teruiEmergentDualScaling2021].

It is abundantly clear that ecosystem complexity in natural systems is the rule, not the exception. Early theoretical and empirical work has assumed simple habitat structure as a necessity. However, habitat heterogeneity, such as prey refugia, and dispersal between connected habitat patches allow communities to stabilize and persist through space and time [@pedersenNonhierarchicalDispersalPromotes2016; @mougiFoodwebComplexityMetacommunity2016]. Complex ecosystem structure is an extrinsic factor that can affect FCL in communities. Incorporating a realistic understanding of ecosystem structural complexity may improve our perception of communities in naturally complex systems.

## Acknowledgements

We thank C Perovich for thoughtful discussions in the early stages of this project. This material is based upon work supported by the National Science Foundation through the Division of Environmental Biology (DEB 2015634).

## Author contributions

JP developed the theoretical model of trophic dynamics with input from AT. JP and AT ran the simulations, and made the figures. JP wrote the first draft, while AT and JF contributed significantly to the final version.

# References
