---
output:
  pdf_document:
    latex_engine: xelatex
    includes:
      before_body: title.tex
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, encoding = encoding, output_dir = "document_output")
      })
header-includes:
  \pagenumbering{gobble}
  \usepackage{amsmath}
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE)

options(knitr.kable.NA = '')

```

```{=tex}
\newpage
\pagenumbering{arabic}
```
## Table S1 Parameter values

Parameter values used for the main and sensitivity analysis.

```{r table_param}

source(here::here("code/table_param.R"))
knitr::kable(df_value, format = "markdown")

```

\pagebreak

```{r table_sensitivity}

source(here::here("code/table_stvy.R"))

j <- 1

## conditional text
c_text <- c("ecosystem size",
            "ecosystem complexity")

table_stvy_chunk <- knit_chunk <- NULL

for(i in 1:length(table_stvy)) {
  
  table_legend <- paste0("Sensitivity analysis of the ", c_text[i]," effect on food chain length. Parameter estimates of linear regression models are shown. The response variable is the Spearman's rank correlation between food chain length and ", c_text[i],". Response and explanatory variables (i.e., simulation parameters) were standardized (mean = 0, SD = 1) before the analysis.")
  
  knit_chunk <- paste0("## Table S", i + j, " Sensitivity analysis for ", c_text[i]," \n",
                       table_legend,
                       "\n```{r table_s", i + j,", results='asis'}
                       \n\n
                       table_stvy[[", i,"]]
                       \n\n
                       ```\n",
                       "\n\\pagebreak\n")
  
  table_stvy_chunk <- c(table_stvy_chunk, knit_chunk)  
  
}

```

`r paste(knit(text = table_stvy_chunk), collapse = '\n')`

\pagebreak

```{r si_figure_fcl}

source(here::here("code/figure_si_fcl.R"))

j <- 0

## conditional text
c_text <- c("ecosystem size",
            "ecosystem complexity")

fig_fcl_chunk <- knit_chunk <- NULL

for(i in 1:length(list_g_fcl)) {
  
  K <- length(list_g_fcl[[i]])
  
  for(k in 1:K) {
    
      figure_legend <- paste0(str_to_sentence(c_text[i])," effect on food chain length and occupancies of constituent species. Lines and shades represent loess curves fitted to the simulated data and 95% confidence intervals. In this simulation, the following values of parameters were used: $\\theta$ = ", df_param$theta[k], ", $\\sigma_l$ = ", df_param$sd_disturb_lon[k], ", and $\\sigma_h$ = ", df_param$sd_disturb_source[k], ".")
  
  knit_chunk <- paste0("## Figure S", K * (i - 1) + k + j, " ", str_to_sentence(c_text[i]), " effect on food chain length", " \n",
                       "\n```{r figure_s", K * (i - 1) + k + j,", fig.height = 10, fig.width = 11.5}
                       \n\n
                       list_g_fcl[[", i, "]][[", k, "]]
                       \n\n
                       ```\n",
                       figure_legend,
                       "\n\\pagebreak\n")
  
  fig_fcl_chunk <- c(fig_fcl_chunk, knit_chunk)  

  }
  
}

```

`r paste(knit(text = fig_fcl_chunk), collapse = '\n')`
